tkstore/basket/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from basket import views

app_name = 'basket'

urlpatterns = [path('', views.basket_summary, name='basket_summary'),
               ]

tkstore/tkstore/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from shop import views
from shop.views import ContactView, CreateCategory, CreateProduct, SignUpView
from django.urls import include

app_name = 'shop'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.product_all, name='product_all'),
    path('<slug:slug>', views.product_detail, name='product_detail'),
    path('shop/<slug:category_slug>/', views.category_list, name='category_list'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('basket/', include('basket.urls', namespace='basket')),
    path("shop/newcategory", CreateCategory.as_view(), name="create_category"),
    path("shop/newproduct", CreateProduct.as_view(), name="create_product"),
    path("sign-up/", SignUpView.as_view(), name="sign-up"),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tkstore/basket/models.py
from django.db import models

# Create your models here.

tkstore/shop/models.py
from django.db import models

from django.urls import reverse
from django.contrib.auth.models import User

app_name = 'shop'


# Create your models here
class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = "category"
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category_list', args={self.slug})


class Product(models.Model):
    category = models.ForeignKey(Category, related_name="products", on_delete=models.CASCADE)
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='images/', blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveBigIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='product_creator', default=True)

    class Meta:
        verbose_name_plural = "Products"
        ordering = ("-created",)
        # index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product_detail', args={self.slug})

tkstore/shop/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import Group


class ContactForm(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    phone = forms.IntegerField(required=False)
    message = forms.CharField(widget=forms.Textarea, required=False)


class SignUpForm(UserCreationForm):
    def save(self, commit=True):
        created_user = super().save(commit)
        basic_group = Group.objects.get(name="basic")
        created_user.groups.add(basic_group)
        basic_group.save()

        return created_user

tkstore/basket/views.py
from django.shortcuts import render


# Create your views here.
def basket_summary(request):
    return render(request, 'summary.html')

tkstore/shop/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Category, Product
from django.views.generic import TemplateView, ListView, CreateView, DetailView, UpdateView, DeleteView, FormView
from .forms import ContactForm, SignUpForm


# Create your views here.
def product_all(request):
    products = Product.objects.all()
    return render(request, 'home.html', {'products': products})


def category_list(request, category_slug=None):
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.objects.filter(category=category)
    return render(request, 'category.html', {'category': category, 'products': products})


def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug, available=True)
    return render(request, 'single.html', {'product': product})


def categories(request):
    return {
        'categories': Category.objects.all()
    }


class ContactView(FormView):
    template_name = "contact.html"
    form_class = ContactForm
    # success_url = reverse_lazy("movies")


class CreateCategory(CreateView):
    template_name = "create_category.html"
    model = Category
    fields = "__all__"
    permission_required = "viewer.add_movie"


class CreateProduct(CreateView):
    template_name = "create_product.html"
    model = Product
    fields = "__all__"
    permission_required = "viewer.add_movie"


class SignUpView(CreateView):
    template_name = "registration/create_account.html"
    form_class = SignUpForm

tkstore/shop/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>{% block title %}My shop{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-light bg-white border-bottom">
            <div class="container-fluid">
                <a class="navbar-brand" href="/">THE O STORE</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                    aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">
                        <li class="nav-item active">
                            <a class="nav-link" aria-current="page" href="/">Home</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Shop by Category
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url "product_all" %}">All</a></li>
                                {% for c in categories %}
                                <li {% if category.slug == c.slug %}class="selected" {% endif %}>
                                    <a class="dropdown-item" href="{{ c.get_absolute_url }}">{{ c.name|title }}</a>
                                </li>
                                {% endfor %}
                            </ul>
                        </li>
                    </ul>
                     <a type="button" role="button" href="{% url 'basket:basket_summary' %}"
                        class="btn btn-outline-secondary">

                        {% with total_qty=basket|length %}
                            <div id="basket-qty" class="d-inline-flex">
                                {% if total_qty > 0 %}
                                    {{ total_qty }}
                                {% else %}
                                    0
                                {% endif %}
                            </div>
                        {% endwith %}

                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-basket" viewBox="0 0 16 16">
                            <path d="M5.757 1.071a.5.5 0 0 1 .172.686L3.383 6h9.234L10.07 1.757a.5.5 0 1 1 .858-.514L13.783 6H15a1 1 0 0 1 1 1v1a1 1 0 0 1-1 1v4.5a2.5 2.5 0 0 1-2.5 2.5h-9A2.5 2.5 0 0 1 1 13.5V9a1 1 0 0 1-1-1V7a1 1 0 0 1 1-1h1.217L5.07 1.243a.5.5 0 0 1 .686-.172zM2 9v4.5A1.5 1.5 0 0 0 3.5 15h9a1.5 1.5 0 0 0 1.5-1.5V9H2zM1 7v1h14V7H1zm3 3a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0v-3A.5.5 0 0 1 4 10zm2 0a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0v-3A.5.5 0 0 1 6 10zm2 0a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0v-3A.5.5 0 0 1 8 10zm2 0a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0v-3a.5.5 0 0 1 .5-.5zm2 0a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0v-3a.5.5 0 0 1 .5-.5z"/>
                        </svg>
                        Basket
                    </a>
                </div>
            </div>
        </nav>
    </header>

    <div id="content">{% block content %} {% endblock %}</div>
</body>
</html>

tkstore/shop/templates/category.html
{% extends "./base.html" %}
{% load static %}
{% block title %}
{% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}


<main>
  <div class="album py-5 bg-light">
    <div class="container">

      <div class="pb-3 h5">{{category.name|title}}</div>
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">

        {% for product in products %}

        <div class="col">
          <div class="card shadow-sm">
          <img class="img-fluid" alt="Responsive image" src="{{ product.image.url }}">

            <div class="card-body">
              <p class="card-text">
                <a class="text-dark text-decoration-none" href="{{ product.get_absolute_url }}">{{ product.name }}</a>
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted">learn more..</small>
              </div>
            </div>
          </div>
        </div>

        {% endfor %}

      </div>
    </div>
  </div>


</main>

{% endblock %}>

tkstore/shop/templates/contact.html
{% extends "./base.html" %}


{% block content %}
<h2>Get in touch with us</h2>
<form method="post">
   {% csrf_token %}
   {{ form.as_p }}
   <input type="submit" value="Contact us" class="btn btn-primary">


</form>

{%endblock %}

tkstore/shop/templates/create_category.html
{% extends "base.html" %}


{% block content %}
<h2>Add category</h2>
<form method="post">
   {% csrf_token %}
   {{ form.as_p }}
   <input type="submit" value="Create category" class="btn btn-primary">


</form>

{%endblock %}

tkstore/shop/templates/create_product.html
{% extends "base.html" %}


{% block content %}
<h2>Add product</h2>
<form method="post">
   {% csrf_token %}
   {{ form.as_p }}
   <input type="submit" value="Create product" class="btn btn-primary">


</form>

{%endblock %}

tkstore/shop/templates/home.html
{% extends "./base.html" %}
{% load static %}
{% block title %}Home{% endblock %}
{% block content %}


<main>

  <section class="py-5 text-center container">
    <div class="row py-lg-3">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="h1 fw-bold">Search, Buy, Enjoy</h1>
        <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator,
          etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.</p>
        <p>
          <a href="sign-up/" class="btn btn-primary my-2">Create an account</a>
        </p>
      </div>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">

      <div class="pb-3 h5">Shop Category</div>
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">

        {% for category in categories %}

        <div class="col">
          <div class="card shadow-sm">


            <div class="card-body">
              <p class="card-text">
                <a class="text-dark text-decoration-none" href="{{ category.get_absolute_url }}">{{ category.name }}</a>
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted">discover more..</small>
              </div>
            </div>
          </div>
        </div>

        {% endfor %}

      </div>
    </div>
  </div>


</main>

{% endblock %}

tkstore/shop/templates/product.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

tkstore/shop/templates/single.html
{% extends "./base.html" %}
{% load static %}
{% block title %}
{{ product.name }}
{% endblock %}
{% block content %}
<div class="container">
    <main class="pt-5">
        <div class="row g-3">
            <div class="col-md-5 col-lg-5 order-md-first bg-light">
                <img class="img-fluid mx-auto d-block" width="200px" alt="Responsive image" src="{{ product.image.url }}">
            </div>
            <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">
                <h1 class="mb-0 h4">{{ product.name }}</h1>
                <p><span class="lead">{{ product.name }}</span> (Spec)</p>
                <p>{{ product.description|slice:":355" }}...</p>
                <div class="border">
                    <div class="col border-bottom">
                        <div class="row p-3">
                            <div class="col-6">Your price</div>
                            <div class="col-6 text-end"><span class="h4 fw-bold">€{{ product.price }}</span></div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="row p-3">
                            <div class="col-6">
                                <label for="select">Qty</label>
                                <select id="select">
                                    <option value="">1</option>
                                    <option value="">2</option>
                                    <option value="">3</option>
                                    <option value="">4</option>
                                </select>

                            </div>
                            <div class="col-6 text-end"><button type="button" class="btn btn-secondary btn-sm">Add to
                                    basket</button></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>

</div>
{% endblock %}

tkstore/shop/templates/summary.html
{% extends "./base.html" %}
{% load static %}
{% block title %}Basket Summary{% endblock %}
{% block content %}

<h1>This is the basket summary page</h1>

{% endblock %}